# Generated by Django 3.2.7 on 2021-11-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
